export interface Department {
  id: number;
  department: string;
  departmentCoordinator: string;
  city: string;
  email: string;
}

// Generated list of 100 mock departments
export const departments: Department[] = [
  {
    id: 1,
    department: "Conducere",
    departmentCoordinator: "Marius Cîmpean",
    city: "Arad",
    email: "conducere.arad@firma.ro",
  },
  {
    id: 2,
    department: "Resurse Umane",
    departmentCoordinator: "Elena Marin",
    city: "Timișoara",
    email: "hr.timisoara@firma.ro",
  },
  {
    id: 3,
    department: "Financiar",
    departmentCoordinator: "Radu Pavel",
    city: "Brașov",
    email: "financiar.brasov@firma.ro",
  },
  {
    id: 4,
    department: "IT",
    departmentCoordinator: "Ioana Petrescu",
    city: "Constanța",
    email: "it.constanta@firma.ro",
  },
  {
    id: 5,
    department: "Marketing",
    departmentCoordinator: "Vlad Munteanu",
    city: "Oradea",
    email: "marketing.oradea@firma.ro",
  },
  {
    id: 6,
    department: "Vanzări",
    departmentCoordinator: "Cristina Dobre",
    city: "București",
    email: "vanzari.bucuresti@firma.ro",
  },
  {
    id: 7,
    department: "Logistică",
    departmentCoordinator: "George Sandu",
    city: "Ploiești",
    email: "logistica.ploiesti@firma.ro",
  },
  {
    id: 8,
    department: "Control Calitate",
    departmentCoordinator: "Oana Rusu",
    city: "Iași",
    email: "qc.iasi@firma.ro",
  },
  {
    id: 9,
    department: "Achiziții",
    departmentCoordinator: "Dragos Neagu",
    city: "Arad",
    email: "achizitii.arad@firma.ro",
  },
  {
    id: 10,
    department: "Juridic",
    departmentCoordinator: "Laura Stoica",
    city: "Craiova",
    email: "juridic.craiova@firma.ro",
  },
  {
    id: 11,
    department: "Proiectare",
    departmentCoordinator: "Mihai Voicu",
    city: "Sibiu",
    email: "proiectare.sibiu@firma.ro",
  },
  {
    id: 12,
    department: "Mentenanță",
    departmentCoordinator: "Daniela Toma",
    city: "Baia Mare",
    email: "mentenanta.baia@firma.ro",
  },
  {
    id: 13,
    department: "Transport",
    departmentCoordinator: "Adrian Ciobanu",
    city: "Suceava",
    email: "transport.suceava@firma.ro",
  },
  {
    id: 14,
    department: "Formare Profesională",
    departmentCoordinator: "Camelia Georgescu",
    city: "Târgu Mureș",
    email: "training.mures@firma.ro",
  },
  {
    id: 15,
    department: "Analiză Date",
    departmentCoordinator: "Florin Enache",
    city: "Pitești",
    email: "analiza.pitesti@firma.ro",
  },
  {
    id: 16,
    department: "Relații Clienți",
    departmentCoordinator: "Simona Zaharia",
    city: "Galați",
    email: "clienti.galati@firma.ro",
  },
  {
    id: 17,
    department: "Conducere Regională",
    departmentCoordinator: "Lucian Iliescu",
    city: "Satu Mare",
    email: "regionala.satumare@firma.ro",
  },
  {
    id: 18,
    department: "Control Resurse",
    departmentCoordinator: "Anca Preda",
    city: "Alba Iulia",
    email: "ctrlres.alba@firma.ro",
  },
  {
    id: 19,
    department: "Planificare Producție",
    departmentCoordinator: "Stefan Costache",
    city: "Botoșani",
    email: "prod.botosani@firma.ro",
  },
  {
    id: 20,
    department: "Consultanță Training",
    departmentCoordinator: "Iulia Barbu",
    city: "Deva",
    email: "training.deva@firma.ro",
  },
  {
    id: 21,
    department: "Management Achiziții",
    departmentCoordinator: "Robert Albu",
    city: "Zalău",
    email: "achizitii.zalau@firma.ro",
  },
  {
    id: 22,
    department: "Sisteme IT",
    departmentCoordinator: "Alina Popescu",
    city: "Cluj-Napoca",
    email: "it.cluj@firma.ro",
  },
  {
    id: 23,
    department: "HR Proiecte",
    departmentCoordinator: "Sorin Vasile",
    city: "Bacău",
    email: "hr.bacau@firma.ro",
  },
  {
    id: 24,
    department: "Tehnic Retele",
    departmentCoordinator: "Carmen Ilie",
    city: "București",
    email: "retehnic.buc@firma.ro",
  },
  {
    id: 25,
    department: "Proiectare",
    departmentCoordinator: "Marius Gheorghe",
    city: "Piatra Neamț",
    email: "proiectare.neamt@firma.ro",
  },
  {
    id: 26,
    department: "Vânzări Consultanță",
    departmentCoordinator: "Roxana Iacob",
    city: "Râmnicu Vâlcea",
    email: "vanzari.valcea@firma.ro",
  },
  {
    id: 27,
    department: "Comunicații",
    departmentCoordinator: "Cosmin Dragomir",
    city: "Giurgiu",
    email: "comm.giurgiu@firma.ro",
  },
  {
    id: 28,
    department: "Recrutare",
    departmentCoordinator: "Ana Tudor",
    city: "Târgoviște",
    email: "recrutare.tgv@firma.ro",
  },
  {
    id: 29,
    department: "Achiziții",
    departmentCoordinator: "Bogdan Lupu",
    city: "Focșani",
    email: "achizitii.focsani@firma.ro",
  },
  {
    id: 30,
    department: "SSM",
    departmentCoordinator: "Diana Costin",
    city: "Slatina",
    email: "ssm.slatina@firma.ro",
  },
  {
    id: 31,
    department: "Dezvoltare Back-End",
    departmentCoordinator: "Paul Marinescu",
    city: "Buzău",
    email: "backend.buzau@firma.ro",
  },
  {
    id: 32,
    department: "Logistică",
    departmentCoordinator: "Ioan Cristea",
    city: "Tulcea",
    email: "log.tulcea@firma.ro",
  },
  {
    id: 33,
    department: "Control Resurse",
    departmentCoordinator: "Gabriela Dincă",
    city: "Reșița",
    email: "resurse.resita@firma.ro",
  },
  {
    id: 34,
    department: "Asigurări",
    departmentCoordinator: "Doru Stan",
    city: "Slobozia",
    email: "asigurari.slob@firma.ro",
  },
  {
    id: 35,
    department: "Contabilitate",
    departmentCoordinator: "Silvia Ene",
    city: "Roman",
    email: "contab.roman@firma.ro",
  },
  {
    id: 36,
    department: "Evenimente",
    departmentCoordinator: "Adelina Lungu",
    city: "Câmpina",
    email: "evt.campina@firma.ro",
  },
  {
    id: 37,
    department: "Automatizări",
    departmentCoordinator: "Emil Tănase",
    city: "Alexandria",
    email: "auto.alexandria@firma.ro",
  },
  {
    id: 38,
    department: "Comunicare",
    departmentCoordinator: "Sorina Avram",
    city: "Sighetu Marmației",
    email: "comm.sighet@firma.ro",
  },
  {
    id: 39,
    department: "Transport",
    departmentCoordinator: "Dan Bălan",
    city: "Petroșani",
    email: "trans.petrosani@firma.ro",
  },
  {
    id: 40,
    department: "Analist Credit",
    departmentCoordinator: "Teodora Pop",
    city: "Mediaș",
    email: "credit.medias@firma.ro",
  },
  {
    id: 41,
    department: "Mentenanță",
    departmentCoordinator: "Valentin Boaru",
    city: "Curtea de Argeș",
    email: "mentenanta.arges@firma.ro",
  },
  {
    id: 42,
    department: "Resurse Umane",
    departmentCoordinator: "Corina Nedelcu",
    city: "Bistrița",
    email: "hr.bistrita@firma.ro",
  },
  {
    id: 43,
    department: "IT Dezvoltare",
    departmentCoordinator: "Rareș Mihai",
    city: "Făgăraș",
    email: "it.fagaras@firma.ro",
  },
  {
    id: 44,
    department: "Gestiune",
    departmentCoordinator: "Lavinia Moraru",
    city: "Caransebeș",
    email: "gest.carans@firma.ro",
  },
  {
    id: 45,
    department: "Control Calitate",
    departmentCoordinator: "Cristian Voinea",
    city: "Tecuci",
    email: "qc.tecuci@firma.ro",
  },
  {
    id: 46,
    department: "Consultanță Financiară",
    departmentCoordinator: "Ileana Apostol",
    city: "Calafat",
    email: "fin.calafat@firma.ro",
  },
  {
    id: 47,
    department: "Tehnic IT",
    departmentCoordinator: "Victor Toma",
    city: "Lugoj",
    email: "it.lugoj@firma.ro",
  },
  {
    id: 48,
    department: "Proiectare",
    departmentCoordinator: "Mariana Grigore",
    city: "Mangalia",
    email: "proj.mangalia@firma.ro",
  },
  {
    id: 49,
    department: "Comunicare",
    departmentCoordinator: "Roxana Udrea",
    city: "Câmpulung",
    email: "comm.campul@firma.ro",
  },
  {
    id: 50,
    department: "Tehnic",
    departmentCoordinator: "Tudor Popa",
    city: "Hunedoara",
    email: "tech.hunedoara@firma.ro",
  },
  {
    id: 51,
    department: "Resurse Umane",
    departmentCoordinator: "Lidia Nistor",
    city: "Roșiorii de Vede",
    email: "hr.rosiori@firma.ro",
  },
  {
    id: 52,
    department: "Analiză HR",
    departmentCoordinator: "Lavinia Ciobanu",
    city: "Târgu Jiu",
    email: "hr.targujiu@firma.ro",
  },
  {
    id: 53,
    department: "Proiecte IT",
    departmentCoordinator: "Adrian Stan",
    city: "Buzău",
    email: "proj.it.buzau@firma.ro",
  },
  {
    id: 54,
    department: "Marketing Regional",
    departmentCoordinator: "Raluca Pavel",
    city: "Sibiu",
    email: "mkt.sibiu@firma.ro",
  },
  {
    id: 55,
    department: "Financiar Proiecte",
    departmentCoordinator: "Ioan Tudor",
    city: "Baia Mare",
    email: "fin.proj.bm@firma.ro",
  },
  {
    id: 56,
    department: "Control Achiziții",
    departmentCoordinator: "Andreea Iliescu",
    city: "Brăila",
    email: "ctrl.ach.braila@firma.ro",
  },
];
