export type User = {
  id: number;
  name: string;
  position: string;
  department: string;
  city: string;
  email: string;
  phone: string;
  store?: Store;
  type: "user";
};

export const users: User[] = [
  {
    id: 8421,
    name: "Elena Marin",
    position: "Analist Financiar",
    department: "Financiar",
    city: "Timisoara",
    store: {
      id: 1,
      name: "Arad 1",
    },
    email: "elena.marin82@gmail.com",
    phone: "0721553482",
    type: "user",
  },
  {
    id: 3489,
    name: "Radu Pavel",
    position: "Manager IT",
    department: "IT",
    city: "Brasov",
    email: "radu.pavel.it@gmail.com",
    phone: "0734981212",
    type: "user",
  },
  {
    id: 9112,
    name: "Ioana Petrescu",
    position: "Coordonator Proiect",
    department: "Proiectare",
    city: "Constanta",
    email: "ioana.petrescu@yahoo.com",
    phone: "0742893471",
    type: "user",
  },
  {
    id: 4502,
    name: "Vlad Munteanu",
    position: "Inginer Electric",
    department: "Mentenanta",
    city: "Oradea",
    email: "vlad.munteanu78@gmail.com",
    phone: "0723987344",
    type: "user",
  },
  {
    id: 7305,
    name: "Cristina Dobre",
    position: "Consultant HR",
    department: "Resurse Umane",
    city: "Bucuresti",
    email: "cristina.dobre.hr@gmail.com",
    phone: "0736123855",
    type: "user",
  },
  {
    id: 1247,
    name: "George Sandu",
    position: "Tehnician Service",
    department: "Service Tehnic",
    city: "Ploiesti",
    email: "george.sandu.service@gmail.com",
    phone: "0721183940",
    type: "user",
  },
  {
    id: 3674,
    name: "Oana Rusu",
    position: "Specialist Marketing",
    department: "Marketing",
    city: "Iasi",
    email: "oana.rusu.marketing@gmail.com",
    phone: "0742335981",
    type: "user",
  },
  {
    id: 8890,
    name: "Dragos Neagu",
    position: "Administrator Retea",
    department: "IT",
    city: "Arad",
    email: "dragos.neagu.retea@gmail.com",
    phone: "0723345670",
    type: "user",
  },
  {
    id: 6123,
    name: "Laura Stoica",
    position: "Coordonator Achizitii",
    department: "Achizitii",
    city: "Craiova",
    email: "laura.stoica@gmail.com",
    phone: "0741123489",
    type: "user",
  },
  {
    id: 3298,
    name: "Mihai Voicu",
    position: "Operator Call Center",
    department: "Relatii Clienti",
    city: "Sibiu",
    email: "mihai.voicu.callcenter@yahoo.com",
    phone: "0733559002",
    type: "user",
  },
  {
    id: 9902,
    name: "Daniela Toma",
    position: "Manager Regional",
    department: "Conducere Regionala",
    city: "Baia Mare",
    email: "daniela.toma.region@gmail.com",
    phone: "0721674893",
    type: "user",
  },
  {
    id: 2084,
    name: "Adrian Ciobanu",
    position: "Coordonator Depozit",
    department: "Logistica",
    city: "Suceava",
    email: "adrian.ciobanu.logistica@gmail.com",
    phone: "0731982345",
    type: "user",
  },
  {
    id: 7340,
    name: "Camelia Georgescu",
    position: "Inspector Calitate",
    department: "Control Calitate",
    city: "Targu Mures",
    email: "camelia.georgescu.cc@gmail.com",
    phone: "0728934321",
    type: "user",
  },
  {
    id: 8017,
    name: "Florin Enache",
    position: "Programator Front-End",
    department: "IT Dezvoltare",
    city: "Pitesti",
    email: "florin.enache.dev@gmail.com",
    phone: "0743100923",
    type: "user",
  },
  {
    id: 4923,
    name: "Simona Zaharia",
    position: "Reprezentant Vanzari",
    department: "Vanzari",
    city: "Galati",
    email: "simona.zaharia.sales@gmail.com",
    phone: "0723456781",
    type: "user",
  },
  {
    id: 6872,
    name: "Lucian Iliescu",
    position: "Coordonator Tehnic",
    department: "Tehnic",
    city: "Satu Mare",
    email: "lucian.iliescu.tech@gmail.com",
    phone: "0738110021",
    type: "user",
  },
  {
    id: 5631,
    name: "Anca Preda",
    position: "Responsabil Juridic",
    department: "Juridic",
    city: "Alba Iulia",
    email: "anca.preda.juridic@gmail.com",
    phone: "0729453123",
    type: "user",
  },
  {
    id: 7542,
    name: "Stefan Costache",
    position: "Planificator Productie",
    department: "Productie",
    city: "Botosani",
    email: "stefan.costache.prod@gmail.com",
    phone: "0741029384",
    type: "user",
  },
  {
    id: 4126,
    name: "Iulia Barbu",
    position: "Consultant Training",
    department: "Formare Profesionala",
    city: "Deva",
    email: "iulia.barbu.training@gmail.com",
    phone: "0739283741",
    type: "user",
  },
  {
    id: 9503,
    name: "Robert Albu",
    position: "Analist Date",
    department: "Analiza Date",
    city: "Zalau",
    email: "robert.albu.data@gmail.com",
    phone: "0729012387",
    type: "user",
  },
  {
    id: 1001,
    name: "Alina Popescu",
    position: "Specialist Financiar",
    department: "Financiar",
    city: "Cluj-Napoca",
    email: "alina.popescu.fin@gmail.com",
    phone: "0721998765",
    type: "user",
  },
  {
    id: 1002,
    name: "Sorin Vasile",
    position: "Administrator Sistem",
    department: "IT",
    city: "Bacau",
    email: "sorin.vasile.sys@gmail.com",
    phone: "0732111234",
    type: "user",
  },
  {
    id: 1003,
    name: "Carmen Ilie",
    position: "Manager HR",
    department: "Resurse Umane",
    city: "Bucuresti",
    email: "carmen.ilie.hr@gmail.com",
    phone: "0723556789",
    type: "user",
  },
  {
    id: 1004,
    name: "Marius Gheorghe",
    position: "Tehnician Retele",
    department: "IT",
    city: "Piatra Neamt",
    email: "marius.gheorghe.net@gmail.com",
    phone: "0742123456",
    type: "user",
  },
  {
    id: 1005,
    name: "Roxana Iacob",
    position: "Inginer Proiectant",
    department: "Proiectare",
    city: "Ramnicu Valcea",
    email: "roxana.iacob.proj@gmail.com",
    phone: "0731987654",
    type: "user",
  },
  {
    id: 1006,
    name: "Cosmin Dragomir",
    position: "Consultant Vanzari",
    department: "Vanzari",
    city: "Giurgiu",
    email: "cosmin.dragomir.sales@gmail.com",
    phone: "0721992345",
    type: "user",
  },
  {
    id: 1007,
    name: "Ana Tudor",
    position: "Recrutor",
    department: "Resurse Umane",
    city: "Targoviste",
    email: "ana.tudor.recrutare@gmail.com",
    phone: "0733123988",
    type: "user",
  },
  {
    id: 1008,
    name: "Bogdan Lupu",
    position: "Manager Achizitii",
    department: "Achizitii",
    city: "Focsani",
    email: "bogdan.lupu.achizitii@gmail.com",
    phone: "0723432121",
    type: "user",
  },
  {
    id: 1009,
    name: "Diana Costin",
    position: "Responsabil SSM",
    department: "Protectia Muncii",
    city: "Slatina",
    email: "diana.costin.ssm@gmail.com",
    phone: "0742338899",
    type: "user",
  },
  {
    id: 1010,
    name: "Paul Marinescu",
    position: "Programator Back-End",
    department: "IT Dezvoltare",
    city: "Buzau",
    email: "paul.marinescu.dev@gmail.com",
    phone: "0734110022",
    type: "user",
  },
  {
    id: 1011,
    name: "Ioan Cristea",
    position: "Planificator Logistic",
    department: "Logistica",
    city: "Tulcea",
    email: "ioan.cristea.log@gmail.com",
    phone: "0729445566",
    type: "user",
  },
  {
    id: 1012,
    name: "Gabriela Dinca",
    position: "Analist Resurse",
    department: "Control Resurse",
    city: "Resita",
    email: "gabriela.dinca.cr@gmail.com",
    phone: "0741889234",
    type: "user",
  },
  {
    id: 1013,
    name: "Doru Stan",
    position: "Specialist Asigurari",
    department: "Juridic",
    city: "Slobozia",
    email: "doru.stan.legal@gmail.com",
    phone: "0732541278",
    type: "user",
  },
  {
    id: 1014,
    name: "Silvia Ene",
    position: "Operator Facturare",
    department: "Contabilitate",
    city: "Roman",
    email: "silvia.ene.cont@gmail.com",
    phone: "0723114499",
    type: "user",
  },
  {
    id: 1015,
    name: "Adelina Lungu",
    position: "Coordonator Evenimente",
    department: "Marketing",
    city: "Campina",
    email: "adelina.lungu.marketing@gmail.com",
    phone: "0743998877",
    type: "user",
  },
  {
    id: 1016,
    name: "Emil Tanase",
    position: "Tehnician Automatizari",
    department: "Tehnic",
    city: "Alexandria",
    email: "emil.tanase.tech@gmail.com",
    phone: "0736332211",
    type: "user",
  },
  {
    id: 1017,
    name: "Sorina Avram",
    position: "Specialist Comunicare",
    department: "Comunicare",
    city: "Sighetu Marmatiei",
    email: "sorina.avram.comm@gmail.com",
    phone: "0728224455",
    type: "user",
  },
  {
    id: 1018,
    name: "Dan Balan",
    position: "Coordonator Transport",
    department: "Logistica",
    city: "Petrosani",
    email: "dan.balan.transport@gmail.com",
    phone: "0741223344",
    type: "user",
  },
  {
    id: 1019,
    name: "Teodora Pop",
    position: "Analist Credit",
    department: "Financiar",
    city: "Medias",
    email: "teodora.pop.credit@gmail.com",
    phone: "0723456723",
    type: "user",
  },
  {
    id: 1020,
    name: "Valentin Boaru",
    position: "Inginer Mecanic",
    department: "Mentenanta",
    city: "Curtea de Arges",
    email: "valentin.boaru.ment@gmail.com",
    phone: "0739221134",
    type: "user",
  },
  {
    id: 1021,
    name: "Corina Nedelcu",
    position: "Inspector Resurse",
    department: "Resurse Umane",
    city: "Bistrita",
    email: "corina.nedelcu.rh@gmail.com",
    phone: "0743884321",
    type: "user",
  },
  {
    id: 1022,
    name: "Rares Mihai",
    position: "Programator Java",
    department: "IT Dezvoltare",
    city: "Fagaras",
    email: "rares.mihai.java@gmail.com",
    phone: "0721348922",
    type: "user",
  },
  {
    id: 1023,
    name: "Lavinia Moraru",
    position: "Operator Gestiune",
    department: "Gestiune",
    city: "Caransebes",
    email: "lavinia.moraru.gest@gmail.com",
    phone: "0736541123",
    type: "user",
  },
  {
    id: 1024,
    name: "Cristian Voinea",
    position: "Responsabil Calitate",
    department: "Control Calitate",
    city: "Tecuci",
    email: "cristian.voinea.cc@gmail.com",
    phone: "0742789981",
    type: "user",
  },
  {
    id: 1025,
    name: "Ileana Apostol",
    position: "Consultant Financiar",
    department: "Financiar",
    city: "Calafat",
    email: "ileana.apostol.fin@gmail.com",
    phone: "0723998812",
    type: "user",
  },
  {
    id: 1026,
    name: "Victor Toma",
    position: "Tehnician IT",
    department: "IT",
    city: "Lugoj",
    email: "victor.toma.tech@gmail.com",
    phone: "0731992388",
    type: "user",
  },
];

export default users;
